---
Name: fromholdio-listings
After:
  - gridfieldextensions
---

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.ListingsCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'ListingsCache'

Fromholdio\Listings\Forms\GridFieldListedPagesAddNewButton:
  showEmptyString: true
